name: Publish Docker image

on:
  push:
    branches:
      - main
    paths:
      - 'fetch-validator-status/**'  # Build only if their are changes in this directory
  
  workflow_dispatch:
    inputs:
      ref:
        required: false
        type: string
        description: "This is the tag version, don't include the v like this 2.4.6, if you dont provide a version we will get the latest tag"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository main
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Required due to the way Git works, without it this action won't be able to find any or the correct tags

      - name: Extract latest version from Git tag, excludind the v.
        run: |
          LATEST_TAG=$(git describe --tags `git rev-list --tags --max-count=1` | cut -c2-)
          echo "LATEST_TAG=$LATEST_TAG" >> $GITHUB_ENV
          echo "LATEST_TAG=$LATEST_TAG"

      - name: Checkout repository specific tag
        uses: actions/checkout@v4
        with:
          ref: v${{ inputs.ref || env.LATEST_TAG }}

      - name: Log in to the GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set lowercase username
        run: echo "USERNAME=$(echo ${{ github.repository_owner }} | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

      - name: Build the Docker image
        run: docker build -t ghcr.io/${{ env.USERNAME }}/${{ github.event.repository.name }}/indy-node-monitor:${{ inputs.ref || env.LATEST_TAG  }} ./fetch-validator-status/

      - name: Push the Docker image
        run: docker push ghcr.io/${{ env.USERNAME }}/${{ github.event.repository.name }}/indy-node-monitor:${{ inputs.ref || env.LATEST_TAG }}
